project:
  type: website
  render:
    - "*.qmd"
    - "!utils/_setup.qmd"
website:
  title: "✈️"
  page-navigation: true
  description: "Visualiser les émissions de CO2 liées à une mesure de restriction de liaison aérienne relativement à des durées de trajets ferroviaires dans le cadre. L'étude portera sur les liaisons aériennes entre les 10 plus grandes agglomérations de la Métropole française. Elle permettra de quantifier et de localiser les émissions de CO2 évitées avec des mesures hypothétiques d'interdictions de liaisons aériennes lorsqu'une alternative ferroviaire existe en moins de 3h30, 4h30, 5h30..."
  site-url: "https://inseefrlab.github.io/funathon2024_sujet1/"
  
  repo-url: "https://github.com/InseeFrLab/funathon2024_sujet1"
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right:
    - text: "License"
      href: LICENCE

  navbar:
    align: center
    collapse-below: lg
 
    right:
      - icon: github
        href: "https://github.com/InseeFrLab/funathon2024_sujet1"
        aria-label: GitHub

    left:
      - text: "Présentation du sujet"
        href: index.qmd
      - text: "API"
        href: 1-api.qmd
      - text: "Analyse des données"
        href: 2-analyse.qmd
      - text: "Datavisualisation"
        href: 3-dataviz.qmd

format:
  html:
    theme:
      light: cosmo
    toc: true
    reference-location: margin
    code-copy: true
    code-overflow: wrap

execute: 
  eval: true
  cache: true
  warning: false
